name: Build PDF File
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex Wipro-Dokumentation.tex
            biber Wipro-Dokumentation
            makeglossaries Wipro-Dokumentation
            pdflatex Wipro-Dokumentation.tex
            pdflatex Wipro-Dokumentation.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Wipro-Dokumentation.pdf
          path: Wipro-Dokumentation.pdf
