name: Build PDF File
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Wipro-Dokumentation.tex
          args: -pdf -cd -f Wipro-Dokumentation.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Wipro-Dokumentation.pdf
          path: Wipro-Dokumentation.pdf
